language: cpp
sudo: required

matrix:
  include:
    - os: osx
      osx_image: xcode10.1
      env:
        - MATRIX_EVAL="brew install cmake"
    - os: linux
      addons:
      apt:
        sources:
          - ubuntu-toolchain-r-test
        packages:
          - g++
          - gcc
          - libboost-dev
          - cmake
        update: true

install:
  - git clone --depth 1 https://github.com/catchorg/Catch2.git && cd Catch2 && cmake -Bbuild -H. -DBUILD_TESTING=OFF && cmake --build build/ --target install
  - rm -rf build && mkdir build && cd build && cmake .. && cmake --build .

script:
  - cd build && ./test_autolayout
notifications:
  email:
    on_failure: change
    on_success: never
